(()=>{"use strict";
const KEY="armwrestle-pwa-v1";
let state={matches:[],training:[]};
try{state=JSON.parse(localStorage.getItem(KEY)||'{"matches":[],"training":[]}')}catch(e){}
if(!Array.isArray(state.matches))state.matches=[];if(!Array.isArray(state.training))state.training=[];
const $=id=>document.getElementById(id),save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const form={type:"Practice",arm:"Right",singleStrap:"No",side:"Left",result:"Win",go:"I hit first",trainingArm:"Both",quality:"Good"};
let scope="Tournament",roundNumber=0;
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="dashboard")renderDashboard();if(id==="history")renderHistory();if(id==="opponents")renderOpponents();if(id==="training")renderTraining()}
document.querySelectorAll(".tabs button").forEach(b=>b.addEventListener("click",()=>page(b.dataset.page)));
$("dashNewMatch").addEventListener("click",()=>page("match"));
for(let w=130;w<=500;w+=5){$("myWeight").insertAdjacentHTML("beforeend",`<option value="${w}">${w} lb</option>`);$("oppWeight").insertAdjacentHTML("beforeend",`<option value="${w}">${w} lb</option>`)}
for(let h=48;h<=96;h++){const ft=Math.floor(h/12),inch=h%12,label=ft+"'"+inch+'"';$("myHeight").insertAdjacentHTML("beforeend",`<option value="${h}">${label}</option>`);$("oppHeight").insertAdjacentHTML("beforeend",`<option value="${h}">${label}</option>`)}
for(let i=1;i<=10;i++)$("sets").insertAdjacentHTML("beforeend",`<option>${i}</option>`);
for(let i=1;i<=30;i++)$("reps").insertAdjacentHTML("beforeend",`<option>${i}</option>`);
function group(id,key){$(id).querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{form[key]=b.dataset.value;$(id).querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x===b));if(key==="type"){let sm=form.type==="Supermatch";$("singleFields").classList.toggle("hidden",sm);$("superFields").classList.toggle("hidden",!sm);if(sm&&!$("rounds").children.length)addRound()}}))}
group("matchType","type");group("arm","arm");group("singleStrap","singleStrap");group("tableSide","side");group("result","result");group("go","go");group("trainingArm","trainingArm");group("quality","quality");
function addRound(){roundNumber++;let d=document.createElement("div");d.className="round";let rr="Win",gg="I hit first",rs="No";d.innerHTML=`<h3>Round ${roundNumber}</h3><label>Strap</label><div class="segmented rstrap"><button type="button" data-value="No" class="selected">No</button><button type="button" data-value="Yes">Yes</button></div><label>Result</label><div class="segmented rr"><button type="button" data-value="Win" class="selected">WIN</button><button type="button" data-value="Loss">LOSS</button></div><label>Who got the GO?</label><div class="segmented rg"><button type="button" data-value="I hit first" class="selected">I hit first</button><button type="button" data-value="Opponent hit first">They hit first</button><button type="button" data-value="Even">Even</button><button type="button" data-value="Unclear">Unclear</button></div><div class="two"><label>YOUR TECHNIQUE<select class="rm"><option>Not recorded</option><option>Toproll</option><option>Hook</option><option>Press</option><option>King's Move</option><option>Other</option></select></label><label>OPPONENT'S TECHNIQUE<select class="ro"><option>Not recorded</option><option>Toproll</option><option>Hook</option><option>Press</option><option>King's Move</option><option>Other</option></select></label></div><label>Match length<select class="rl"><option>Not recorded</option><option>Under 5 seconds</option><option>5–30 seconds</option><option>Over 30 seconds</option></select></label>`;$("rounds").appendChild(d);d.querySelectorAll(".rstrap button").forEach(b=>b.addEventListener("click",()=>{rs=b.dataset.value;d.querySelectorAll(".rstrap button").forEach(x=>x.classList.toggle("selected",x===b))}));d.querySelectorAll(".rr button").forEach(b=>b.addEventListener("click",()=>{rr=b.dataset.value;d.querySelectorAll(".rr button").forEach(x=>x.classList.toggle("selected",x===b))}));d.querySelectorAll(".rg button").forEach(b=>b.addEventListener("click",()=>{gg=b.dataset.value;d.querySelectorAll(".rg button").forEach(x=>x.classList.toggle("selected",x===b))}));d.getRound=()=>({strap:rs,result:rr,go:gg,myTech:d.querySelector(".rm").value,oppTech:d.querySelector(".ro").value,length:d.querySelector(".rl").value})}
$("addRound").addEventListener("click",addRound);
$("matchForm").addEventListener("submit",e=>{e.preventDefault();let opponent=$("opponent").value.trim();if(!opponent)return alert("Enter an opponent.");let m={id:Date.now(),opponent,matchType:form.type,arm:form.arm,side:form.side,myWeight:$("myWeight").value,oppWeight:$("oppWeight").value,myHeight:$("myHeight").value,oppHeight:$("oppHeight").value,weightClass:$("weightClass").value,comments:$("comments").value.trim()};if(form.type==="Supermatch"){m.rounds=[...$("rounds").children].map(x=>x.getRound());let w=m.rounds.filter(r=>r.result==="Win").length,l=m.rounds.filter(r=>r.result==="Loss").length;m.result=w>l?"Win":"Loss"}else{m.strap=form.singleStrap;m.result=form.result;m.go=form.go;m.myTech=$("myTech").value;m.oppTech=$("oppTech").value;m.length=$("length").value}state.matches.unshift(m);save();e.target.reset();alert("Match saved.");page("history")});
$("trainingForm").addEventListener("submit",e=>{e.preventDefault();state.training.unshift({id:Date.now(),category:$("tCategory").value,arm:form.trainingArm,sets:$("sets").value,reps:$("reps").value,resistance:$("resistance").value,intensity:$("intensity").value,quality:form.quality,comments:$("trainingComments").value.trim()});save();e.target.reset();alert("Training saved.");page("training")});
function rec(ms){let w=ms.filter(m=>m.result==="Win").length;return[w,ms.length-w]}
function techniqueStats(ms){let mine={},against={};const one=(r)=>{if(r.myTech&&r.myTech!=="Not recorded"){mine[r.myTech]??={w:0,l:0};r.result==="Win"?mine[r.myTech].w++:mine[r.myTech].l++}if(r.oppTech&&r.oppTech!=="Not recorded"){against[r.oppTech]??={w:0,l:0};r.result==="Win"?against[r.oppTech].l++:against[r.oppTech].w++}};ms.forEach(m=>m.matchType==="Supermatch"?m.rounds.forEach(one):one(m));return{mine,against}}
function renderDashboard(){let t=rec(state.matches.filter(m=>m.matchType==="Tournament")),s=rec(state.matches.filter(m=>m.matchType==="Supermatch")),p=rec(state.matches.filter(m=>m.matchType==="Practice"));$("tourRecord").textContent=t.join("–");$("superRecord").textContent=s.join("–");$("practiceRecord").textContent=p.join("–");$("trainingCount").textContent=state.training.length;let ms=state.matches.filter(m=>m.matchType===scope),st=techniqueStats(ms),all=Object.entries(st.mine).map(([k,v])=>({k,...v,n:v.w+v.l})),fav=all.sort((a,b)=>b.n-a.n)[0],good=all.filter(x=>x.n>=3).sort((a,b)=>b.w/b.n-a.w/a.n)[0],bad=all.filter(x=>x.n>=3).sort((a,b)=>a.w/a.n-b.w/b.n)[0],opp=Object.entries(st.against).map(([k,v])=>({k,...v,n:v.w+v.l})).filter(x=>x.n>=3).sort((a,b)=>b.w/b.n-a.w/a.n)[0];$("myStats").innerHTML=`<div class="two"><div class="rec"><b>Favorite technique</b><br>${fav?esc(fav.k):"Not enough data"}</div><div class="rec"><b>Most successful</b><br>${good?esc(good.k)+" · "+Math.round(good.w/good.n*100)+"% win rate":"Need 3+ attempts"}</div><div class="rec"><b>Least successful</b><br>${bad?esc(bad.k)+" · "+Math.round(bad.w/bad.n*100)+"% win rate":"Need 3+ attempts"}</div><div class="rec"><b>Best opponent technique against you</b><br>${opp?esc(opp.k)+" · opponents win "+Math.round(opp.w/opp.n*100)+"%":"Need 3+ attempts"}</div></div>`;$("recent").innerHTML=state.matches.slice(0,5).map(m=>`<div class="entry"><div class="row"><b>${esc(m.opponent)}</b><b class="${m.result==="Win"?"win":"loss"}">${m.result.toUpperCase()}</b></div><div class="muted">${esc(m.matchType)} · ${esc(m.arm)} arm · strap ${esc(m.strap)}${m.matchType==="Supermatch"?" · "+m.rounds.length+" rounds":""}</div></div>`).join("")||'<p class="muted">No matches yet.</p>'}
function renderHistory(){$("historyList").innerHTML=state.matches.map(m=>`<div class="entry"><div class="row"><b>${esc(m.opponent)}</b><b class="${m.result==="Win"?"win":"loss"}">${m.result.toUpperCase()}</b></div><div class="muted">${esc(m.matchType)} · ${esc(m.arm)} · table side when facing head referee: ${esc(m.side)}${m.matchType==="Supermatch"?" · "+m.rounds.length+" rounds · strap by round":" · strap "+esc(m.strap||"No")}</div>${m.comments?`<div style="margin-top:7px">${esc(m.comments)}</div>`:""}</div>`).join("")||'<p class="muted">No matches yet.</p>'}
function renderTraining(){$("trainingList").innerHTML=state.training.slice(0,10).map(t=>`<div class="entry"><b>${esc(t.category)}</b><div class="muted">${esc(t.arm)} · ${esc(t.sets)} sets × ${esc(t.reps)} reps · ${esc(t.intensity)} · ${esc(t.quality)}</div>${t.comments?`<div style="margin-top:7px">${esc(t.comments)}</div>`:""}</div>`).join("")||'<p class="muted">No training logs yet.</p>'}
function renderOpponents(){let names=[...new Set(state.matches.map(m=>m.opponent))].sort();$("opponentList").innerHTML=names.map(n=>`<option value="${esc(n)}">`).join("");$("profiles").innerHTML=names.map(n=>{let ms=state.matches.filter(m=>m.opponent===n);return `<div class="entry" data-opponent="${esc(n)}" tabindex="0"><div class="row"><b>${esc(n)}</b><b>${rec(ms)[0]}–${rec(ms)[1]}</b></div><span class="tag">Practice ${rec(ms.filter(m=>m.matchType==="Practice")).join("–")}</span><span class="tag">Tournament ${rec(ms.filter(m=>m.matchType==="Tournament")).join("–")}</span><span class="tag">Supermatch ${rec(ms.filter(m=>m.matchType==="Supermatch")).join("–")}</span></div>`}).join("")||'<p class="muted">No opponents yet.</p>';document.querySelectorAll("#profiles [data-opponent]").forEach(x=>x.addEventListener("click",()=>showOpponent(x.dataset.opponent)))}
function showOpponent(name){let ms=state.matches.filter(m=>m.opponent===name),weights=[...new Set(ms.map(m=>m.oppWeight).filter(Boolean))].sort((a,b)=>a-b);let heights=[...new Set(ms.map(m=>m.oppHeight).filter(Boolean))].sort((a,b)=>a-b);let sections=["Practice","Tournament","Supermatch"].map(type=>{let x=ms.filter(m=>m.matchType===type),r=rec(x),st=techniqueStats(x),best=Object.entries(st.mine).map(([k,v])=>({k,...v,n:v.w+v.l})).filter(x=>x.n>=3).sort((a,b)=>b.w/b.n-a.w/a.n)[0];return `<div class="rec"><b>${type}: ${r[0]}–${r[1]}</b><br><span class="muted">${best?"Best recorded technique: "+esc(best.k)+" · "+Math.round(best.w/best.n*100)+"%":"Not enough technique data"}</span></div>`}).join("");$("opponentDetail").classList.remove("hidden");$("opponentDetail").innerHTML=`<div class="row"><h2>${esc(name)}</h2><button id="closeOpp">Close</button></div><p><b>Weight history:</b> ${weights.length?weights.join(", ")+" lb":"Not recorded"}</p><p><b>Height history:</b> ${heights.length?heights.map(h=>Math.floor(h/12)+"\'"+(h%12)+"\"").join(", "):"Not recorded"}</p>${sections}`;$("closeOpp").addEventListener("click",()=>$("opponentDetail").classList.add("hidden"))}
$("statScope").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{scope=b.dataset.value;$("statScope").querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x===b));renderDashboard()}));
renderDashboard();renderHistory();renderTraining();renderOpponents();
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
})();